---
title: "Compte rendu reunion 9 Decembre"
author: "Victor Aragno"
date: "16 decembre 2019"
output: html_document
---

#Recapitulatif :

  Le projet SC n°14 est d'ameliorer les previsions d'abondance par la CPUE. Dans ce
cadre trois axes ont ete soulignes :

- Les Potentiels interets de l'utilisation des variables environnementales.

- L'etude des differences entre la CPUE pour la peche sous bancs objets « vise » avec
celle sous bancs objets « au hasard ».

- L'etude de l'augmentation de la CPUE pour les annees 2003-2005.

#Objectif de mon travai l :

  Lors du calcul de la CPUE, une augmentation suspecte est apparue dans certaines
zones de l'ocean indien lors des annees entre 2003 et 2005. Ce travail consiste donc a
approfondir l'etude de la CPUE dans cette periode avec l'hypothese que cette
augmentation ne soit pas ou pas totalement en partie due a une augmentation de
l'abondance.

Le premier element de reponse sera l'evolution de la densite des tailles de thon sur
cette periode et dans ces zones. Une augmentation significative de la moyenne des
tailles de thon captures dans ces zones pourrait pourrait confirmer l'evolution de
l'abondance. Cependant cette hausse de la CPUE est multi-factorielle, certaines
questions seront a approfondir :

- Cette augmentation de la CPUE est elle correlee a une augmentation de la
concentration d'autres organismes / especes ?

- Est-il possible que ces zones a forte CPUE soit des niches jusque-la ignorees par les
pecheurs ?